# Generated by Django 5.1.4 on 2026-06-01 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact message',
                'verbose_name_plural': 'Contact messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=120)),
                ('account_title', models.CharField(max_length=120)),
                ('account_number', models.CharField(max_length=60)),
                ('iban', models.CharField(max_length=60)),
                ('whatsapp_number', models.CharField(help_text='Include country code, e.g. +923001234567', max_length=20)),
                ('payment_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Payment instruction',
                'verbose_name_plural': 'Payment instructions',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clients_helped', models.PositiveIntegerField(default=0)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('conditions_treated', models.PositiveIntegerField(default=0)),
                ('sessions_conducted', models.PositiveIntegerField(default=0)),
                ('about_text', models.TextField(blank=True)),
                ('philosophy_quote', models.CharField(blank=True, max_length=300)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Site setting',
                'verbose_name_plural': 'Site settings',
            },
        ),
    ]
