# Generated by Django 5.1.4 on 2026-06-01 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_type', models.CharField(choices=[('ONLINE', 'Online'), ('INPERSON', 'In-person'), ('BOTH', 'Online or In-person')], default='BOTH', max_length=10)),
                ('is_disabled', models.BooleanField(default=False)),
                ('is_booked', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Available slot',
                'verbose_name_plural': 'Available slots',
                'ordering': ['date', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('date', 'start_time', 'slot_type'), name='unique_slot_per_date_time_type')],
            },
        ),
    ]
