# Generated by Django 5.1.4 on 2026-06-01 20:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('fee_online', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_inperson', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('available_online', models.BooleanField(default=True)),
                ('available_inperson', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
